version: '3.3'
#
# docker-compose.yml — определяет сервисы для разработки и тестирования.

#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.

services:

  db:
    image: postgres:14
    container_name: db
    networks:
      - my_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data


  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my_network
    volumes:
      - ..:/workspace
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres?currentSchema=public
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - JWT_SECRET=23b503ac73e68ca5ec1a9c946b7b28f2b26af49e2b9942e1a20286f047a5a832
      - JWT_EXPIRATION_DAYS=30


networks:
  my_network:
volumes:
  postgres-data: