#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

server:
  port: 8081

spring:
  application:
    name: bank-cards-app
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/effective_mobile?currentSchema=public}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

jwt:
  secret: ${JWT_SECRET:23b503ac73e68ca5ec1a9c946b7b28f2b26af49e2b9942e1a20286f047a5a832}
  expiration-days: ${JWT_EXPIRATION_DAYS:30}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  info:
    title: @project.name@
    version: @project.version@
    description: @project.description@